# Generated by Django 3.0.2 on 2020-02-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='ycomp',
            new_name='YearsAtCompany',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='ycurole',
            new_name='YearsInCurrentRole',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='yprom',
            new_name='YearsSinceLastPromotion',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='ycman',
            new_name='YearsWithCurrManager',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='jobsat',
            new_name='JobSatisfaction',
        ),

    ]
